spring:
  application:
    name=brainz
  jpa:
    show-sql: true
  datasource:
    driver-class-name=org.hsqldb.jdbc.JDBCDriver
    url=jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
    username=sa
    password=
    jpa.hibernate.ddl-auto=create-drop
    jpa.hibernate.format_sql=true
    
area: 
  fileLocation: /home/jose/Downloads/mbdump/mbdump
  fileName: area
  immutable: org.nanotek.brainz.base.AnyBase
  delegateMap:     
    areaId: 0 
    gid: 1 
    areaName: 2 
    typeId: 3 
    editsPending: 4 
    lastUpdated: 5 
    beginYear: 6 
    beginMonth: 7 
    beginDay: 8 
    endYear: 9 
    endMonth: 10 
    endDay: 11
    ended: 12 

artist:
  fileLocation: /home/jose/Downloads/mbdump/mbdump
  fileName: artist
  immutable: org.nanotek.brainz.base.record.ArtistRecord
  delegateMap:
    artistId: 0
    gid: 1
    artistName: 2
    sortName: 3
    beginDateYear: 4
    beginDateMonth: 5
    beginDateDay: 6
    endDateYear: 7
    endDateMonth: 8
    endDateDay: 9
    typeId: 10
    areaId: 11
    genderId: 12 
    comment: 13
    editsPending: 14
    lastUpdated: 15
    
genre:
  fileLocation: /home/jose/Downloads/mbdump/mbdump
  fileName: genre
  immutable: org.nanotek.brainz.base.record.GenreRecord
  delegateMap:
    genreId: 0
    gid: 1
    genreName: 2

artisttype: 
  fileLocation: /home/jose/Downloads/mbdump/mbdump
  fileName: artist_type
  immutable: org.nanotek.brainz.base.record.ArtistTypeRecord
  baseClass: org.nanotek.brainz.base.entity.ArtistType
  delegateMap:   
    typeId: 0
    typeName: 1
    parent: 2
    childOrder: 3
    description: 4
    gid: 5

artistaliastype: 
  fileLocation: /home/jose/Downloads/mbdump/mbdump
  fileName: artist_alias_type
  immutable: org.nanotek.brainz.base.record.ArtistAliasTypeRecord
  baseClass: org.nanotek.brainz.base.entity.ArtistAliasType
  delegateMap:   
    typeId: 0
    typeName: 1
    parent: 2
    childOrder: 3
    description: 4
    gid: 5   
    
fileconfig:
  area:
    fileLocation: /home/jose/Downloads/mbdump/mbdump
    fileName: area
    immutable: org.nanotek.brainz.base.record.AreaRecord
    delegateMap:     
      areaId: 0 
      gid: 1 
      areaName: 2
  artist:
    fileLocation: /home/jose/Downloads/mbdump/mbdump/artist
    fileName: artist
    immutable: org.nanotek.brainz.base.record.ArtistRecord
    delegateMap:
      artistId: 0
      gid: 1
      artistName: 2
      sortName: 3
  genre:
    fileLocation: /home/jose/Downloads/mbdump/mbdump
    fileName: genre
    immutable: org.nanotek.brainz.base.record.GenreRecord
    delegateMap:
      genreId: 0
      gid: 1
      genreName: 2
  artisttype: 
    fileLocation: /home/jose/Downloads/mbdump/mbdump
    fileName: artist_type
    immutable: org.nanotek.brainz.base.record.ArtistTypeRecord
    baseClass: org.nanotek.brainz.base.entity.ArtistType
    delegateMap:     
      typeId: 0
      typeName: 1
      parent: 2
      childOrder: 3
      description: 4
      gid: 5
  artistaliastype: 
    fileLocation: /home/jose/Downloads/mbdump/mbdump
    fileName: artist_alias_type
    immutable: org.nanotek.brainz.base.record.ArtistAliasTypeRecord
    baseClass: org.nanotek.brainz.base.entity.ArtistAliasType
    delegateMap:   
      typeId: 0
      typeName: 1
      parent: 2
      childOrder: 3
      description: 4
      gid: 5   
  
      
          
       